### ISSUE TITLE
Code for Plotme

### ISSUE THREAD

**Issue by Mnhrt** [senkergroup/morty#5]
@carstenblt 

Wäre es möglich den Source Code for Plotme auch in die Senker Group zu stellen?

VG M

**Comment by carstenblt** [comment]
Plotme?

**Comment by Mnhrt** [comment]
Renée meinte, dass du das fürs ACIV Praktikum geschrieben hast. Das kleine Programm zum Einlesen der Messungen und Vergleich mit der Simulation.

PS: Ich hatte dir auch noch mal Wegen der Verlängerung des Zugangs ne Mail geschrieben.

**Comment by carstenblt** [comment]
Ui. Ich schaue.

P.S. Glaubt Jürgen noch an meine Promotion?

**Comment by Mnhrt** [comment]
Danke fürs Schauen :) 
Bezüglich deiner Promotion bin ich nicht informiert, sry. Ich bekomme als IT Beauftragter nur auch immer die Verlängerungsanfragen und dachte mir ich frag mal nach, da ich noch nichts gehört habe.

**Comment by Mnhrt** [comment]
Alternativ kannst du mir natürlich auch den Code schicken und ich mach es lokal oder füge es online hinz. Dann hast du nicht so viel Arbeit damit.

**Comment by carstenblt** [comment]
Du hast ne E-Mail!
